<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="KIT1085" ignored="1" name="Test" tests="2" failures="1" timestamp="07 Jul 2019 11:51:34 GMT" time="16.069" errors="0">
  <testcase name="TitleVerification" time="5.65" classname="testNG.Practice"/>
  <testcase name="CartVerification" time="10.385" classname="testNG.Practice">
    <failure type="java.lang.AssertionError" message="expected [3] but found [x 3]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [x 3]
at testNG.Practice.CartVerification(Practice.java:65)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- CartVerification -->
  <testcase name="f" time="0.0" classname="testNG.SampleTest">
    <ignored/>
  </testcase> <!-- f -->
</testsuite> <!-- Test -->
