<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="16069" started-at="2019-07-07T11:51:18Z" finished-at="2019-07-07T11:51:34Z">
    <groups>
      <group name="Sanity">
        <method signature="Practice.CartVerification()[pri:2, instance:testNG.Practice@73f792cf]" name="CartVerification" class="testNG.Practice"/>
        <method signature="Practice.TitleVerification()[pri:1, instance:testNG.Practice@73f792cf]" name="TitleVerification" class="testNG.Practice"/>
      </group> <!-- Sanity -->
      <group name="regression">
        <method signature="Practice.TitleVerification()[pri:1, instance:testNG.Practice@73f792cf]" name="TitleVerification" class="testNG.Practice"/>
      </group> <!-- regression -->
    </groups>
    <test name="Test" duration-ms="16069" started-at="2019-07-07T11:51:18Z" finished-at="2019-07-07T11:51:34Z">
      <class name="testNG.Practice">
        <test-method status="PASS" signature="beforeSuite(java.lang.String)[pri:0, instance:testNG.Practice@73f792cf]" name="beforeSuite" is-config="true" duration-ms="3119" started-at="2019-07-07T11:51:15Z" finished-at="2019-07-07T11:51:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="TitleVerification()[pri:1, instance:testNG.Practice@73f792cf]" name="TitleVerification" duration-ms="5650" started-at="2019-07-07T11:51:18Z" finished-at="2019-07-07T11:51:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TitleVerification -->
        <test-method status="FAIL" signature="CartVerification()[pri:2, instance:testNG.Practice@73f792cf]" name="CartVerification" duration-ms="10385" started-at="2019-07-07T11:51:24Z" finished-at="2019-07-07T11:51:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [3] but found [x 3]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [3] but found [x 3]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testNG.Practice.CartVerification(Practice.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CartVerification -->
      </class> <!-- testNG.Practice -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
